### ISSUE TITLE
People should be able to select multiple items in their order

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/Haldis#9]
What if I want a pakske frieten with some vleesje? We can't list all the items and all their combinations possible.

Checkboxes are the way to go, not dropdowns.

**Comment by Silox** [comment]
Instead of checkboxes; this is nice too for autocompletion and everything: https://github.com/applegrew/django-select2

**Comment by Silox** [comment]
This also influences the display of the orders. If I for example order a small pakske with joppie and someone else orders a small pakske with mayonaise, these should be listed as `1 small pakske with joppie` and `1 small pakske with mayonaise` and not as `2 small pakskes`, `1 joppie` and `1 mayonaise`

**Comment by SirDestrox** [comment]
Do not agree, most, if not all items, will be handled separately. It is for the courier more convenient if all "small pakskes" are grouped. That way he can order for example 6 "small pakskes" instead of having to count them all. Afterwards he can order all sauces. But your issue does apply for Chinese food.

**Comment by redfast00** [comment]
No longer an issue now that we have HLDS
